#include "common.h"
#include <sys/statvfs.h>

//Session ID -- Generated by Server (random number)
int getSid(void) 
{ 
	srand(time(0)); 
        int id = rand(); 
    	XDEBUG("sid: %d\n", id); 
	return id;
} 

struct sockaddr_in getSA(int srvfd)
{
    struct sockaddr_in addr;
    socklen_t addr_size = sizeof(struct sockaddr_in);
    int res = getpeername(srvfd, (struct sockaddr *)&addr, &addr_size);
    if( res < 0)
       perror("");
    char clientip[20];
    strcpy(clientip, inet_ntoa(addr.sin_addr));
    XDEBUG(" source ip %s\n", clientip);

    return addr;
}

int initClientSocket(int addr, int port, struct sockaddr_in *si_me)
{
  int sockfd = socket(AF_INET, SOCK_DGRAM, 0);
  si_me->sin_port = htons(port);
  si_me->sin_addr.s_addr = addr;

  return sockfd;
}

int initSrvSocket(int port, struct sockaddr_in *si_me)
{
  int sockfd = sockfd = socket(AF_INET, SOCK_DGRAM, 0);
  memset(si_me, '\0', sizeof(*si_me));
  si_me->sin_port = htons(port);
  
  int rc = bind(sockfd, (const struct sockaddr *)si_me, sizeof(struct sockaddr_in));
  if (rc < 0)
  {
     perror("Server is running");
     return -1;
  }
  return sockfd;
}

long getAvailableSpace(const char* path)
{
  struct statvfs stat;
  
  if (statvfs(path, &stat) != 0) {
    // error happens, just quits here
    return -1;
  }

  // the available size is f_bsize * f_bavail
  return stat.f_bsize * stat.f_bavail;
}

int getResourceInfo(char* reqFile)
{
    struct stat resInfo;
    int exist = stat(reqFile, &resInfo);
    if(exist == 0)
    {
        int sz = resInfo.st_size;
        char szstr[20];
        if (sz < 1024)
          sprintf(szstr, "%d bytes", sz);
        else if (sz < 1024*1024)
          sprintf(szstr, "%dkb", sz/1024);
        else if (sz < 1024*1024*1024)
          sprintf(szstr, "%dmb", sz/1024*1024);
        else
          sprintf(szstr, "%dgb", sz/1024*1024*1024);
        XDEBUG("%s:size is %s\n ", reqFile, szstr);
        return sz;
    }
    XDEBUG("%s not found\n", reqFile);
    return -1;
}

// randomly skip packets for testing
int skipAction(int mod)
{
#ifndef DEBUG
   return 0;
#endif
   int r = rand();
   if((r % mod))
   {
      return 0; 
   }
   XDEBUG("Skipped pkt\n");
   return 1;
}

int getIp(char* ipAddrStr)
{
    struct in_addr addr;
    
    int ip = inet_aton(ipAddrStr, &addr);
    if (ip == 0) {
        return 0;
    }
    return addr.s_addr;
}
